'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TrmForgot

    '''<summary>
    '''Forgot_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Forgot_Password As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''Forgot_ConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Forgot_ConfirmPassword As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''DIV_Failed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_Failed As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
