'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _1_doticket

    '''<summary>
    '''TrxCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxCustomerID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxNumberID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxNumberID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxThreadID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxThreadID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxChannel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxChannel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxTicketNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxTicketNumber As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxStatus As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HD_API_Gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HD_API_Gender As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HD_API_NomorPolis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HD_API_NomorPolis As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_Layer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_Layer As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxNomorWhatsApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxNomorWhatsApp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TokenBD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TokenBD As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''GenerateToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenerateToken As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Ticket_DateofTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ticket_DateofTransaction As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''HDMothercare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDMothercare As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDELC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDELC As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDGingersnaps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDGingersnaps As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDJustice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDJustice As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDWilio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDWilio As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDCoach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDCoach As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDKaren control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDKaren As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDWomen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDWomen As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDHavaianas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDHavaianas As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDKanmoretail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDKanmoretail As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDKate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDKate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDNespresso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDNespresso As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DSChannel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DSChannel As Global.System.Web.UI.WebControls.SqlDataSource
End Class
