'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _1_journey_new

    '''<summary>
    '''TrxCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxCustomerID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxLayerEskalasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxLayerEskalasi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HD_Ticket_EnquiryReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HD_Ticket_EnquiryReason As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxEmailID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxGenerateEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxGenerateEmailID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxUserName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxTicketPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxTicketPosition As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxAttachmentEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxAttachmentEmailID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxAttachmentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxAttachmentType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TokenBantuDagang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TokenBantuDagang As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''OrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''GenerateToken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenerateToken As Global.System.Web.UI.WebControls.HiddenField
End Class
