'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="2020HelpdeskShopee")>  _
Partial Public Class R_Interaction_DBMLDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("DefaultConnection").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.R_Interaction")>  _
	Public Function R_Interaction(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="StartDate", DbType:="VarChar(50)")> ByVal startDate As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="EndDate", DbType:="VarChar(50)")> ByVal endDate As String) As ISingleResult(Of R_InteractionResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), startDate, endDate)
		Return CType(result.ReturnValue,ISingleResult(Of R_InteractionResult))
	End Function
End Class

Partial Public Class R_InteractionResult
	
	Private _idTabel As String
	
	Private _TicketSourceName As String
	
	Private _AccountInbound As String
	
	Private _ID As Integer
	
	Private _TicketNumber As String
	
	Private _GenesysID As String
	
	Private _ThreadID As String
	
	Private _ResponseComplaint As String
	
	Private _Status As String
	
	Private _Channel As String
	
	Private _AgentCreate As String
	
	Private _DateCreate As System.Nullable(Of Date)
	
	Private _FirstCreate As String
	
	Private _DispatchTicket As String
	
	Private _DispatchToLayer As String
	
	Private _DispatchToDept As String
	
	Private _DispatchToUserName As String
	
	Private _LEVELUSER As String
	
	Private _InteractionType As String
	
	Private _ORGANIZATION_NAME As String
	
	Private _tanggal As String
	
	Private _leveluser1 As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idTabel", DbType:="VarChar(200)")>  _
	Public Property idTabel() As String
		Get
			Return Me._idTabel
		End Get
		Set
			If (String.Equals(Me._idTabel, value) = false) Then
				Me._idTabel = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TicketSourceName", DbType:="VarChar(300)")>  _
	Public Property TicketSourceName() As String
		Get
			Return Me._TicketSourceName
		End Get
		Set
			If (String.Equals(Me._TicketSourceName, value) = false) Then
				Me._TicketSourceName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccountInbound", DbType:="VarChar(100)")>  _
	Public Property AccountInbound() As String
		Get
			Return Me._AccountInbound
		End Get
		Set
			If (String.Equals(Me._AccountInbound, value) = false) Then
				Me._AccountInbound = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", DbType:="Int NOT NULL")>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TicketNumber", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property TicketNumber() As String
		Get
			Return Me._TicketNumber
		End Get
		Set
			If (String.Equals(Me._TicketNumber, value) = false) Then
				Me._TicketNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GenesysID", DbType:="VarChar(150)")>  _
	Public Property GenesysID() As String
		Get
			Return Me._GenesysID
		End Get
		Set
			If (String.Equals(Me._GenesysID, value) = false) Then
				Me._GenesysID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ThreadID", DbType:="VarChar(150)")>  _
	Public Property ThreadID() As String
		Get
			Return Me._ThreadID
		End Get
		Set
			If (String.Equals(Me._ThreadID, value) = false) Then
				Me._ThreadID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ResponseComplaint", DbType:="Text NOT NULL", CanBeNull:=false, UpdateCheck:=UpdateCheck.Never)>  _
	Public Property ResponseComplaint() As String
		Get
			Return Me._ResponseComplaint
		End Get
		Set
			If (String.Equals(Me._ResponseComplaint, value) = false) Then
				Me._ResponseComplaint = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="VarChar(50)")>  _
	Public Property Status() As String
		Get
			Return Me._Status
		End Get
		Set
			If (String.Equals(Me._Status, value) = false) Then
				Me._Status = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Channel", DbType:="VarChar(100)")>  _
	Public Property Channel() As String
		Get
			Return Me._Channel
		End Get
		Set
			If (String.Equals(Me._Channel, value) = false) Then
				Me._Channel = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AgentCreate", DbType:="VarChar(30)")>  _
	Public Property AgentCreate() As String
		Get
			Return Me._AgentCreate
		End Get
		Set
			If (String.Equals(Me._AgentCreate, value) = false) Then
				Me._AgentCreate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateCreate", DbType:="DateTime")>  _
	Public Property DateCreate() As System.Nullable(Of Date)
		Get
			Return Me._DateCreate
		End Get
		Set
			If (Me._DateCreate.Equals(value) = false) Then
				Me._DateCreate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstCreate", DbType:="VarChar(20)")>  _
	Public Property FirstCreate() As String
		Get
			Return Me._FirstCreate
		End Get
		Set
			If (String.Equals(Me._FirstCreate, value) = false) Then
				Me._FirstCreate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DispatchTicket", DbType:="VarChar(50)")>  _
	Public Property DispatchTicket() As String
		Get
			Return Me._DispatchTicket
		End Get
		Set
			If (String.Equals(Me._DispatchTicket, value) = false) Then
				Me._DispatchTicket = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DispatchToLayer", DbType:="VarChar(50)")>  _
	Public Property DispatchToLayer() As String
		Get
			Return Me._DispatchToLayer
		End Get
		Set
			If (String.Equals(Me._DispatchToLayer, value) = false) Then
				Me._DispatchToLayer = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DispatchToDept", DbType:="VarChar(150)")>  _
	Public Property DispatchToDept() As String
		Get
			Return Me._DispatchToDept
		End Get
		Set
			If (String.Equals(Me._DispatchToDept, value) = false) Then
				Me._DispatchToDept = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DispatchToUserName", DbType:="VarChar(150)")>  _
	Public Property DispatchToUserName() As String
		Get
			Return Me._DispatchToUserName
		End Get
		Set
			If (String.Equals(Me._DispatchToUserName, value) = false) Then
				Me._DispatchToUserName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LEVELUSER", DbType:="VarChar(100)")>  _
	Public Property LEVELUSER() As String
		Get
			Return Me._LEVELUSER
		End Get
		Set
			If (String.Equals(Me._LEVELUSER, value) = false) Then
				Me._LEVELUSER = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InteractionType", DbType:="VarChar(50)")>  _
	Public Property InteractionType() As String
		Get
			Return Me._InteractionType
		End Get
		Set
			If (String.Equals(Me._InteractionType, value) = false) Then
				Me._InteractionType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORGANIZATION_NAME", DbType:="VarChar(500) NOT NULL", CanBeNull:=false)>  _
	Public Property ORGANIZATION_NAME() As String
		Get
			Return Me._ORGANIZATION_NAME
		End Get
		Set
			If (String.Equals(Me._ORGANIZATION_NAME, value) = false) Then
				Me._ORGANIZATION_NAME = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tanggal", DbType:="VarChar(30)")>  _
	Public Property tanggal() As String
		Get
			Return Me._tanggal
		End Get
		Set
			If (String.Equals(Me._tanggal, value) = false) Then
				Me._tanggal = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_leveluser1", DbType:="VarChar(50)")>  _
	Public Property leveluser1() As String
		Get
			Return Me._leveluser1
		End Get
		Set
			If (String.Equals(Me._leveluser1, value) = false) Then
				Me._leveluser1 = value
			End If
		End Set
	End Property
End Class
