'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="2020HelpdeskShopee")>  _
Partial Public Class R_Transaction_DBMLDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("DefaultConnection").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.R_Transaction")>  _
	Public Function R_Transaction(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="XStartDate", DbType:="VarChar(50)")> ByVal xStartDate As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="XEndDate", DbType:="VarChar(50)")> ByVal xEndDate As String) As ISingleResult(Of R_TransactionResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), xStartDate, xEndDate)
		Return CType(result.ReturnValue,ISingleResult(Of R_TransactionResult))
	End Function
End Class

Partial Public Class R_TransactionResult
	
	Private _No As System.Nullable(Of Long)
	
	Private _TicketNumber As String
	
	Private _Channel_Code As String
	
	Private _CategoryName As String
	
	Private _Level1 As String
	
	Private _Level2 As String
	
	Private _Level3 As String
	
	Private _Description As String
	
	Private _TicketStatus As String
	
	Private _CreatedDate As System.Nullable(Of Date)
	
	Private _ClosedDate As System.Nullable(Of Date)
	
	Private _StrPenyebab As String
	
	Private _SkalaPrioritas As String
	
	Private _JenisNasabah As String
	
	Private _NomorRekening As String
	
	Private _Email As String
	
	Private _HP As String
	
	Private _CusStatus As String
	
	Private _Alamat As String
	
	Private _TicketSourceName As String
	
	Private _GenesysID As String
	
	Private _ThreadID As String
	
	Private _NIK As String
	
	Private _AccountInbound As String
	
	Private _AccountID As String
	
	Private _CreatedBy As String
	
	Private _ClosedBy As String
	
	Private _CustomerName As String
	
	Private _PhoneNumber As String
	
	Private _SLA As Integer
	
	Private _UserSolved As String
	
	Private _DateSolvedDisplay As String
	
	Private _DateCreatedDisplay As String
	
	Private _DateClosedDisplay As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_No", DbType:="BigInt")>  _
	Public Property No() As System.Nullable(Of Long)
		Get
			Return Me._No
		End Get
		Set
			If (Me._No.Equals(value) = false) Then
				Me._No = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TicketNumber", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property TicketNumber() As String
		Get
			Return Me._TicketNumber
		End Get
		Set
			If (String.Equals(Me._TicketNumber, value) = false) Then
				Me._TicketNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Channel_Code", DbType:="VarChar(100)")>  _
	Public Property Channel_Code() As String
		Get
			Return Me._Channel_Code
		End Get
		Set
			If (String.Equals(Me._Channel_Code, value) = false) Then
				Me._Channel_Code = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CategoryName", DbType:="VarChar(300) NOT NULL", CanBeNull:=false)>  _
	Public Property CategoryName() As String
		Get
			Return Me._CategoryName
		End Get
		Set
			If (String.Equals(Me._CategoryName, value) = false) Then
				Me._CategoryName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Level1", DbType:="VarChar(250) NOT NULL", CanBeNull:=false)>  _
	Public Property Level1() As String
		Get
			Return Me._Level1
		End Get
		Set
			If (String.Equals(Me._Level1, value) = false) Then
				Me._Level1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Level2", DbType:="VarChar(250) NOT NULL", CanBeNull:=false)>  _
	Public Property Level2() As String
		Get
			Return Me._Level2
		End Get
		Set
			If (String.Equals(Me._Level2, value) = false) Then
				Me._Level2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Level3", DbType:="VarChar(250) NOT NULL", CanBeNull:=false)>  _
	Public Property Level3() As String
		Get
			Return Me._Level3
		End Get
		Set
			If (String.Equals(Me._Level3, value) = false) Then
				Me._Level3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Description", DbType:="VarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Description() As String
		Get
			Return Me._Description
		End Get
		Set
			If (String.Equals(Me._Description, value) = false) Then
				Me._Description = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TicketStatus", DbType:="VarChar(100)")>  _
	Public Property TicketStatus() As String
		Get
			Return Me._TicketStatus
		End Get
		Set
			If (String.Equals(Me._TicketStatus, value) = false) Then
				Me._TicketStatus = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedDate", DbType:="DateTime")>  _
	Public Property CreatedDate() As System.Nullable(Of Date)
		Get
			Return Me._CreatedDate
		End Get
		Set
			If (Me._CreatedDate.Equals(value) = false) Then
				Me._CreatedDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClosedDate", DbType:="DateTime")>  _
	Public Property ClosedDate() As System.Nullable(Of Date)
		Get
			Return Me._ClosedDate
		End Get
		Set
			If (Me._ClosedDate.Equals(value) = false) Then
				Me._ClosedDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StrPenyebab", DbType:="VarChar(250)")>  _
	Public Property StrPenyebab() As String
		Get
			Return Me._StrPenyebab
		End Get
		Set
			If (String.Equals(Me._StrPenyebab, value) = false) Then
				Me._StrPenyebab = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SkalaPrioritas", DbType:="VarChar(100)")>  _
	Public Property SkalaPrioritas() As String
		Get
			Return Me._SkalaPrioritas
		End Get
		Set
			If (String.Equals(Me._SkalaPrioritas, value) = false) Then
				Me._SkalaPrioritas = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_JenisNasabah", DbType:="VarChar(100)")>  _
	Public Property JenisNasabah() As String
		Get
			Return Me._JenisNasabah
		End Get
		Set
			If (String.Equals(Me._JenisNasabah, value) = false) Then
				Me._JenisNasabah = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NomorRekening", DbType:="VarChar(100)")>  _
	Public Property NomorRekening() As String
		Get
			Return Me._NomorRekening
		End Get
		Set
			If (String.Equals(Me._NomorRekening, value) = false) Then
				Me._NomorRekening = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Email", DbType:="VarChar(500)")>  _
	Public Property Email() As String
		Get
			Return Me._Email
		End Get
		Set
			If (String.Equals(Me._Email, value) = false) Then
				Me._Email = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HP", DbType:="VarChar(100)")>  _
	Public Property HP() As String
		Get
			Return Me._HP
		End Get
		Set
			If (String.Equals(Me._HP, value) = false) Then
				Me._HP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusStatus", DbType:="VarChar(50)")>  _
	Public Property CusStatus() As String
		Get
			Return Me._CusStatus
		End Get
		Set
			If (String.Equals(Me._CusStatus, value) = false) Then
				Me._CusStatus = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Alamat", DbType:="NVarChar(MAX)")>  _
	Public Property Alamat() As String
		Get
			Return Me._Alamat
		End Get
		Set
			If (String.Equals(Me._Alamat, value) = false) Then
				Me._Alamat = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TicketSourceName", DbType:="VarChar(300)")>  _
	Public Property TicketSourceName() As String
		Get
			Return Me._TicketSourceName
		End Get
		Set
			If (String.Equals(Me._TicketSourceName, value) = false) Then
				Me._TicketSourceName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GenesysID", DbType:="VarChar(150) NOT NULL", CanBeNull:=false)>  _
	Public Property GenesysID() As String
		Get
			Return Me._GenesysID
		End Get
		Set
			If (String.Equals(Me._GenesysID, value) = false) Then
				Me._GenesysID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ThreadID", DbType:="VarChar(150) NOT NULL", CanBeNull:=false)>  _
	Public Property ThreadID() As String
		Get
			Return Me._ThreadID
		End Get
		Set
			If (String.Equals(Me._ThreadID, value) = false) Then
				Me._ThreadID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NIK", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property NIK() As String
		Get
			Return Me._NIK
		End Get
		Set
			If (String.Equals(Me._NIK, value) = false) Then
				Me._NIK = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccountInbound", DbType:="VarChar(100)")>  _
	Public Property AccountInbound() As String
		Get
			Return Me._AccountInbound
		End Get
		Set
			If (String.Equals(Me._AccountInbound, value) = false) Then
				Me._AccountInbound = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccountID", DbType:="VarChar(150)")>  _
	Public Property AccountID() As String
		Get
			Return Me._AccountID
		End Get
		Set
			If (String.Equals(Me._AccountID, value) = false) Then
				Me._AccountID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedBy", DbType:="VarChar(300)")>  _
	Public Property CreatedBy() As String
		Get
			Return Me._CreatedBy
		End Get
		Set
			If (String.Equals(Me._CreatedBy, value) = false) Then
				Me._CreatedBy = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClosedBy", DbType:="VarChar(300)")>  _
	Public Property ClosedBy() As String
		Get
			Return Me._ClosedBy
		End Get
		Set
			If (String.Equals(Me._ClosedBy, value) = false) Then
				Me._ClosedBy = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerName", DbType:="VarChar(500)")>  _
	Public Property CustomerName() As String
		Get
			Return Me._CustomerName
		End Get
		Set
			If (String.Equals(Me._CustomerName, value) = false) Then
				Me._CustomerName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PhoneNumber", DbType:="VarChar(100)")>  _
	Public Property PhoneNumber() As String
		Get
			Return Me._PhoneNumber
		End Get
		Set
			If (String.Equals(Me._PhoneNumber, value) = false) Then
				Me._PhoneNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SLA", DbType:="Int NOT NULL")>  _
	Public Property SLA() As Integer
		Get
			Return Me._SLA
		End Get
		Set
			If ((Me._SLA = value)  _
						= false) Then
				Me._SLA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserSolved", DbType:="VarChar(300)")>  _
	Public Property UserSolved() As String
		Get
			Return Me._UserSolved
		End Get
		Set
			If (String.Equals(Me._UserSolved, value) = false) Then
				Me._UserSolved = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateSolvedDisplay", DbType:="VarChar(30)")>  _
	Public Property DateSolvedDisplay() As String
		Get
			Return Me._DateSolvedDisplay
		End Get
		Set
			If (String.Equals(Me._DateSolvedDisplay, value) = false) Then
				Me._DateSolvedDisplay = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateCreatedDisplay", DbType:="VarChar(30)")>  _
	Public Property DateCreatedDisplay() As String
		Get
			Return Me._DateCreatedDisplay
		End Get
		Set
			If (String.Equals(Me._DateCreatedDisplay, value) = false) Then
				Me._DateCreatedDisplay = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateClosedDisplay", DbType:="VarChar(30)")>  _
	Public Property DateClosedDisplay() As String
		Get
			Return Me._DateClosedDisplay
		End Get
		Set
			If (String.Equals(Me._DateClosedDisplay, value) = false) Then
				Me._DateClosedDisplay = value
			End If
		End Set
	End Property
End Class
