'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tele_TrxReport

    '''<summary>
    '''dt_strdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_strdate As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''dt_endate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_endate As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ComboAgent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboAgent As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''btn_Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Submit As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''ASPxGridViewExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporter1 As Global.DevExpress.Web.ASPxGridViewExporter

    '''<summary>
    '''XtraHistoryTransaksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XtraHistoryTransaksi As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_Export control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Export As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''DataSourceAgent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataSourceAgent As Global.System.Web.UI.WebControls.SqlDataSource
End Class
