'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TrmNotification

    '''<summary>
    '''TrxID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxDepartmentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxDepartmentID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxVendorID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxVendorID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HdTicketCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdTicketCreate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HdTicketOverSLA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdTicketOverSLA As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HdTicketClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdTicketClosed As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HdTicketEscalation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdTicketEscalation As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
