'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TrmUserAdd

    '''<summary>
    '''TrxID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HDEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDEmail As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDWA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDWA As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDInbound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDInbound As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDOutbound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDOutbound As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDInstagram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDInstagram As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDFacebook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDFacebook As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDTwitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDTwitter As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDTelegram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDTelegram As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDLazada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDLazada As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDShopee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDShopee As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDTokopedia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDTokopedia As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDWalkin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDWalkin As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
