'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TrxAgentSM_New

    '''<summary>
    '''TrxUserAgentId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxUserAgentId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TrxTransaksiID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrxTransaksiID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HDUserAgent_Checkbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDUserAgent_Checkbox As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
